set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR armv7hf)

set(_CMAKE_TOOLCHAIN_LOCATION /usr/bin)
set(_CMAKE_TOOLCHAIN_PREFIX arm-linux-gnueabihf-)
set(_CMAKE_SYSROOT /usr/arm-linux-gnueabihf)
set(CMAKE_C_COMPILER    ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}g++)

include(CMakeFindBinUtils)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} ${_CMAKE_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)