set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(_CMAKE_TOOLCHAIN_LOCATION /usr/bin)
set(_CMAKE_TOOLCHAIN_PREFIX aarch64-linux-gnu-)
set(_CMAKE_LINUX_SYSROOT /usr/aarch64-linux-gnu CACHE PATH "AARCH64 cross compilation system root")
set(CMAKE_C_COMPILER    ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}gcc)
set(CMAKE_CXX_COMPILER  ${_CMAKE_TOOLCHAIN_LOCATION}/${_CMAKE_TOOLCHAIN_PREFIX}g++)

include(CMakeFindBinUtils)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH} ${_CMAKE_LINUX_SYSROOT})

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)

